### Pytorch Tensors

It is the central data abstraction in PyTorch

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[9.3878e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [3]:
# Other factory methods -
zeros = torch.zeros(2, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[9.3880e-35, 0.0000e+00, 3.0867e-01],
         [7.3580e-02, 4.2160e-01, 6.9054e-02]],

        [[9.4613e-35, 0.0000e+00, 9.4614e-35],
         [0.0000e+00, 9.4615e-35, 0.0000e+00]]])


In [7]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[9.3882e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 6.9054e-02]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])


In [8]:
zeros_like_x = torch.empty_like(x)
print(zeros_like_x)
print(zeros_like_x.shape)

tensor([[[9.3882e-35, 0.0000e+00, 2.3694e-38],
         [1.6543e+00, 0.0000e+00, 1.3972e+00]],

        [[2.0000e+00, 1.7108e+00, 0.0000e+00],
         [1.3881e+00, 0.0000e+00, 1.0654e-04]]])
torch.Size([2, 2, 3])


In [9]:
ones_like_x = torch.ones_like(x)
print(ones_like_x)
print(ones_like_x.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])


In [10]:
rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [11]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])


In [12]:
some_integers = torch.tensor((2, 3, 5, 7, 9, 11, 13, 15))
print(some_integers)

tensor([ 2,  3,  5,  7,  9, 11, 13, 15])


In [13]:
more_integers = torch.tensor(((2, 4, 6), (3, 6, 9)))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


In [14]:
few_more_integers = torch.tensor(((2, 4, 6), [3, 6, 9])) # this is interesting
print(few_more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


Tensor Data Types

In [15]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [16]:
b = torch.rand((2, 3), dtype = torch.float64) * 20.
print(b)

tensor([[10.8626,  2.1505, 19.6913],
        [ 0.9956,  1.4148,  5.8364]], dtype=torch.float64)


In [17]:
c = b.to(torch.int32)
print(c)

tensor([[10,  2, 19],
        [ 0,  1,  5]], dtype=torch.int32)


Math and Logic with PyTorch Tensors

In [18]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

In [19]:
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [20]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])

fives = ones + fours

dozens = threes * fours

In [21]:
print(powers2)

tensor([[ 2.,  4.],
        [ 8., 16.]])


In [22]:
print(fives)

tensor([[5., 5.],
        [5., 5.]])


In [23]:
print(dozens)

tensor([[12., 12.],
        [12., 12.]])


Tensor Broadcasting

* Dimensions must match last to first
* One of the dimensions should match
* Can't broadcast with empty tensors

In [24]:
rand = torch.rand(2, 4)
print(rand)

tensor([[0.0703, 0.5105, 0.9451, 0.2359],
        [0.1979, 0.3327, 0.6146, 0.5999]])


In [25]:
new_twos = torch.ones(1, 4) * 2
print(new_twos)

tensor([[2., 2., 2., 2.]])


In [26]:
doubled = rand * new_twos
print(doubled)

tensor([[0.1405, 1.0210, 1.8901, 0.4717],
        [0.3959, 0.6655, 1.2291, 1.1998]])


In [27]:
a = torch.ones(4, 3, 2)
print(a)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [28]:
b = a * torch.rand(3, 2) # dim 1 is absent, 3rd and 2nd dims are identical
print(b)

tensor([[[0.5013, 0.9397],
         [0.8656, 0.5207],
         [0.6865, 0.3614]],

        [[0.5013, 0.9397],
         [0.8656, 0.5207],
         [0.6865, 0.3614]],

        [[0.5013, 0.9397],
         [0.8656, 0.5207],
         [0.6865, 0.3614]],

        [[0.5013, 0.9397],
         [0.8656, 0.5207],
         [0.6865, 0.3614]]])


In [29]:
c = a * torch.rand(3, 1) # dim 1 is absent, 2nd dim is identical and 3rd dim is different
print(c)

tensor([[[0.6493, 0.6493],
         [0.2633, 0.2633],
         [0.4762, 0.4762]],

        [[0.6493, 0.6493],
         [0.2633, 0.2633],
         [0.4762, 0.4762]],

        [[0.6493, 0.6493],
         [0.2633, 0.2633],
         [0.4762, 0.4762]],

        [[0.6493, 0.6493],
         [0.2633, 0.2633],
         [0.4762, 0.4762]]])


In [30]:
d = a * torch.rand(1, 2) # dim 1 is absent, 2nd dimension is different and 3rd dim is identical
print(d)

tensor([[[0.0548, 0.2024],
         [0.0548, 0.2024],
         [0.0548, 0.2024]],

        [[0.0548, 0.2024],
         [0.0548, 0.2024],
         [0.0548, 0.2024]],

        [[0.0548, 0.2024],
         [0.0548, 0.2024],
         [0.0548, 0.2024]],

        [[0.0548, 0.2024],
         [0.0548, 0.2024],
         [0.0548, 0.2024]]])


Math Operations

In [31]:
# common fucntions -
a = torch.rand(2, 4) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) # Clamps all elements in input into the range [ min, max ].

tensor([[ 0.1461,  0.4382, -0.1866,  0.4602],
        [ 0.2551,  0.4715, -0.9238, -0.5724]])
tensor([[0.1461, 0.4382, 0.1866, 0.4602],
        [0.2551, 0.4715, 0.9238, 0.5724]])
tensor([[1., 1., -0., 1.],
        [1., 1., -0., -0.]])
tensor([[ 0.,  0., -1.,  0.],
        [ 0.,  0., -1., -1.]])
tensor([[ 0.1461,  0.4382, -0.1866,  0.4602],
        [ 0.2551,  0.4715, -0.5000, -0.5000]])


In [32]:
# Trigonometric functions
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\n Sine and arcsine: ')
print(angles)
print(sines)
print(inverses)


 Sine and arcsine: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [33]:
# Bitwise Operations
print('\n Bitwise XOR: ')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


 Bitwise XOR: 
tensor([3, 2, 1])


In [34]:
print(b)
print(c)

tensor([ 1,  5, 11])
tensor([ 2,  7, 10])


In [35]:
# comparisons -
print('\n Broadcasted, element-wise equality comparison: ')
d = torch.tensor([[1., 2.], [1., 4.]])
e = torch.ones(1, 2)
print(d)
print(e)


 Broadcasted, element-wise equality comparison: 
tensor([[1., 2.],
        [1., 4.]])
tensor([[1., 1.]])


In [36]:
print(torch.eq(d, e)) # it does it element-wise

tensor([[ True, False],
        [ True, False]])


In [37]:
print(torch.ge(e, d))

tensor([[ True, False],
        [ True, False]])


In [38]:
# reductions
print('\n Reduction Ops: ')
print(torch.max(d)) # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d)) # average
print(torch.std(d)) # standard deviation
print(torch.prod(d)) # product
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements


 Reduction Ops: 
tensor(4.)
4.0
tensor(2.)
tensor(1.4142)
tensor(8.)
tensor([1, 2])


In [39]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) # x unit vector
v2 = torch.tensor([0., 1., 0.]) # y unit vector
m1 = torch.rand(2, 2) # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

In [40]:
print(v1)
print(v2)
print(m1)
print(m2)

tensor([1., 0., 0.])
tensor([0., 1., 0.])
tensor([[0.5395, 0.3686],
        [0.4007, 0.7220]])
tensor([[3., 0.],
        [0., 3.]])


In [41]:
print(torch.cross(v2, v1))

tensor([ 0.,  0., -1.])


In [42]:
m3 = torch.matmul(m1, m2)
print(m3)

tensor([[1.6186, 1.1057],
        [1.2021, 2.1659]])


In [43]:
print(torch.svd(m3))

torch.return_types.svd(
U=tensor([[-0.6102, -0.7923],
        [-0.7923,  0.6101]]),
S=tensor([3.0788, 0.7070]),
V=tensor([[-0.6301, -0.7765],
        [-0.7765,  0.6301]]))


Altering Tensors in Place

In [44]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a: ')
print(a)

a: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [45]:
print(torch.sin(a)) # this operation creates a new tensor in memory
print(a) # a has not changed

tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [46]:
# Now we will do it in place -

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)


b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [47]:
print(torch.sin_(b)) # note the underscore, it is used for in-place operation
print(b) # 'b' has changed

tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [48]:
# On the similar note other mathematical functions behave -

a = torch.ones(2, 2)
b = torch.rand(2, 2)

print("Before: ")
print(a)
print(b)

print("\n After adding : ")
print(a.add_(b))
print(a)
print(b)

print('\n After multiplying: ')
print(b.mul_(b))
print(b)

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8217, 0.2612],
        [0.7375, 0.8328]])

 After adding : 
tensor([[1.8217, 1.2612],
        [1.7375, 1.8328]])
tensor([[1.8217, 1.2612],
        [1.7375, 1.8328]])
tensor([[0.8217, 0.2612],
        [0.7375, 0.8328]])

 After multiplying: 
tensor([[0.6752, 0.0682],
        [0.5439, 0.6936]])
tensor([[0.6752, 0.0682],
        [0.5439, 0.6936]])


In [52]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
print(a)
print(b)

tensor([[0.9877, 0.0352],
        [0.0905, 0.4485]])
tensor([[0.8740, 0.2526],
        [0.6923, 0.7545]])


In [53]:
old_id = id(c)
print(old_id)

139944029920128


In [54]:
print(c)

tensor([[0., 0.],
        [0., 0.]])


In [56]:
d = torch.matmul(a, b, out = c) # multiplying 'a' and 'b' and putting the output in 'c'
print(c)

tensor([[0.8877, 0.2761],
        [0.3896, 0.3613]])


In [57]:
print(d)

tensor([[0.8877, 0.2761],
        [0.3896, 0.3613]])


In [58]:
# 'c' and 'd' has same values, let us also check if c & d are the same object or not.
assert c is d

In [59]:
# yes we saw it is the same object

In [60]:
assert id(c), old_id

In [61]:
torch.rand(2, 2, out = c)
print(c)

tensor([[0.7746, 0.2330],
        [0.8441, 0.9004]])


In [62]:
assert id(c), old_id

In [63]:
# The object remains same as we are doing an inplace operation

Copying Tensors

In [65]:
# This is how any object in Python works as well 

a = torch.ones(2, 2)
b = a

In [66]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [67]:
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [68]:
a[0][1] = 561
print(a)

tensor([[  1., 561.],
        [  1.,   1.]])


In [69]:
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


Say you want to have a separate copy of the data to work on 

In [70]:
a = torch.ones(2, 2)
b = a.clone()

In [71]:
assert b is not a   # different objects in memory ...

In [72]:
print(torch.eq(a, b)) # although different objects in the memory but still have the same content

tensor([[True, True],
        [True, True]])


In [73]:
a[0][1] = 561
print(a)

tensor([[  1., 561.],
        [  1.,   1.]])


In [74]:
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [75]:
a = torch.rand(2, 2, requires_grad = True) # turn on autograd
print(a)

b = a.clone()
print(b)

tensor([[0.3995, 0.6324],
        [0.9464, 0.0113]], requires_grad=True)
tensor([[0.3995, 0.6324],
        [0.9464, 0.0113]], grad_fn=<CloneBackward0>)


In [76]:
c = a.detach().clone()
print(c)

print(a)

tensor([[0.3995, 0.6324],
        [0.9464, 0.0113]])
tensor([[0.3995, 0.6324],
        [0.9464, 0.0113]], requires_grad=True)


Moving to GPU

In [77]:
if torch.cuda.is_available():
  print("We have a GPU !!")
else:
  print("Sorry, CPU only ...")

Sorry, CPU only ...


In [78]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device = 'cuda')  # moving tensors to the GPU
  print(gpu_rand)
else:
  print("Sorry, CPU only ...")

Sorry, CPU only ...


In [79]:
if torch.cuda.is_available():
  my_device = torch.device('cuda') # this is your handle now
else:
  my_device = torch.device('cpu')

print('Device : {}'.format(my_device))

Device : cpu


In [80]:
x = torch.rand(2, 2, device = my_device)
print(x)

tensor([[0.5183, 0.9807],
        [0.6545, 0.4144]])


If you have an existing tensor living on one device, you can move it to another with the to() method. The following line of code creates a tensor on CPU, and move it to whichever device handle you acquired

In [81]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [82]:
print(y)

tensor([[0.0696, 0.4648],
        [0.4491, 0.6265]])


Manipulating Tensor Shapes -

1. Changing the number of dimensions -

When we want to pass a single instance of input to your model. Pytorch models generally expect batches of input. 

For example, imagine having a model that works on 3 x 226 x 226 images (i.e. a 226-pixel square with 3 color channels). When you load and transform it, you will get a tensor shape (3, 226, 226). 

Your model is expecting input shape of (N, 3, 226, 226) where 'N' is the number of images in the batch.

You can make a batch of using unsqueeze()

In [83]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [85]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.8207]]]]])


If we want to do a non-batched computation with that output i.e. expecting a 20-element vector

In [86]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.6818, 0.5057, 0.9335, 0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823,
         0.8637, 0.1891, 0.3952, 0.9176, 0.8960, 0.4887, 0.8625, 0.6191, 0.9935,
         0.1844, 0.6138]])


In [89]:
b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([20])
tensor([0.6818, 0.5057, 0.9335, 0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823,
        0.8637, 0.1891, 0.3952, 0.9176, 0.8960, 0.4887, 0.8625, 0.6191, 0.9935,
        0.1844, 0.6138])


In [94]:
c = torch.rand(2, 2)
print(c.shape)

torch.Size([2, 2])


In [95]:
d = c.squeeze(0)
print(d.shape)

torch.Size([2, 2])


2. Broadcasting

In [99]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3) # trying to multiply a * b will give you a runtime error
c = b.unsqueeze(1) # change to a 2-dimensional tensor, adding new dimension at the end
print(c.shape)

torch.Size([3, 1])


In [100]:
print(a * c)

tensor([[[0.4362, 0.4362],
         [0.2368, 0.2368],
         [0.1394, 0.1394]],

        [[0.4362, 0.4362],
         [0.2368, 0.2368],
         [0.1394, 0.1394]],

        [[0.4362, 0.4362],
         [0.2368, 0.2368],
         [0.1394, 0.1394]],

        [[0.4362, 0.4362],
         [0.2368, 0.2368],
         [0.1394, 0.1394]]])


Both squeeze() and unsqueeze() have an in-place versions using squeeze_() and unsqueeze_()

In [101]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

torch.Size([6, 20, 20])


In [103]:
inputId = output3d.reshape(6 * 20 * 20)
print(inputId.shape)

torch.Size([2400])


In [104]:
inputId

tensor([0.1721, 0.1751, 0.3851,  ..., 0.6032, 0.5349, 0.4536])

In [105]:
# we can also use the following implementation -

print(torch.reshape(output3d, (6 * 20 * 20, )).shape)

torch.Size([2400])


NumPy Bridge

In [106]:
import numpy as np

In [107]:
numpy_array = np.ones((2, 3))
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [108]:
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [109]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

tensor([[0.7441, 0.9803, 0.3956],
        [0.3535, 0.9068, 0.9509]])


In [110]:
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

[[0.74405384 0.98029405 0.39563763]
 [0.35353196 0.90680194 0.9508812 ]]


In [111]:
# Note these converted objects are using the same underlying memory as their source objects
# meaning that changes to one are reflected in the other.

In [112]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)


In [113]:
pytorch_rand[1, 1] = 17
print(numpy_rand)

[[ 0.74405384  0.98029405  0.39563763]
 [ 0.35353196 17.          0.9508812 ]]
