### Pytorch Tensors

It is the central data abstraction in PyTorch

In [1]:
import torch
import math

In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.6300e-35, 0.0000e+00, 5.0447e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3788e-14, 3.6423e-06],
        [2.0699e-19, 3.3738e-12, 7.4086e+28, 6.9397e+22]])


In [4]:
# Other factory methods -
zeros = torch.zeros(2, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [7]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[1.6304e-35, 0.0000e+00, 3.0867e-01],
         [7.3580e-02, 4.2160e-01, 6.9054e-02]],

        [[1.3556e-19, 8.6462e+11, 3.2778e+09],
         [1.4988e+10, 3.2522e+03, 1.3023e+01]]])


In [8]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[1.6303e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 6.4460e-44]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])


In [9]:
zeros_like_x = torch.empty_like(x)
print(zeros_like_x)
print(zeros_like_x.shape)

tensor([[[1.6304e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 1.3312e-43]],

        [[4.4721e+21, 1.5956e+25, 4.7399e+16],
         [3.7293e-08, 8.0101e+00, 5.5095e+11]]])
torch.Size([2, 2, 3])


In [10]:
ones_like_x = torch.ones_like(x)
print(ones_like_x)
print(ones_like_x.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])


In [11]:
rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [12]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])


In [13]:
some_integers = torch.tensor((2, 3, 5, 7, 9, 11, 13, 15))
print(some_integers)

tensor([ 2,  3,  5,  7,  9, 11, 13, 15])


In [14]:
more_integers = torch.tensor(((2, 4, 6), (3, 6, 9)))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


In [15]:
few_more_integers = torch.tensor(((2, 4, 6), [3, 6, 9])) # this is interesting
print(few_more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


Tensor Data Types

In [16]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [20]:
b = torch.rand((2, 3), dtype = torch.float64) * 20.
print(b)

tensor([[17.7174, 14.2091, 18.9694],
        [15.5129,  1.7932, 13.2545]], dtype=torch.float64)


In [21]:
c = b.to(torch.int32)
print(c)

tensor([[17, 14, 18],
        [15,  1, 13]], dtype=torch.int32)


Math and Logic with PyTorch Tensors

In [22]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

In [23]:
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [24]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])

fives = ones + fours

dozens = threes * fours

In [25]:
print(powers2)

tensor([[ 2.,  4.],
        [ 8., 16.]])


In [26]:
print(fives)

tensor([[5., 5.],
        [5., 5.]])


In [27]:
print(dozens)

tensor([[12., 12.],
        [12., 12.]])


Tensor Broadcasting

* Dimensions must match last to first
* One of the dimensions should match
* Can't broadcast with empty tensors

In [28]:
rand = torch.rand(2, 4)
print(rand)

tensor([[0.2941, 0.3788, 0.4567, 0.0649],
        [0.6677, 0.7826, 0.1332, 0.0023]])


In [31]:
new_twos = torch.ones(1, 4) * 2
print(new_twos)

tensor([[2., 2., 2., 2.]])


In [32]:
doubled = rand * new_twos
print(doubled)

tensor([[0.5882, 0.7576, 0.9134, 0.1298],
        [1.3355, 1.5652, 0.2663, 0.0045]])


In [33]:
a = torch.ones(4, 3, 2)
print(a)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [34]:
b = a * torch.rand(3, 2) # dim 1 is absent, 3rd and 2nd dims are identical
print(b)

tensor([[[0.4945, 0.3857],
         [0.9883, 0.4762],
         [0.7242, 0.0776]],

        [[0.4945, 0.3857],
         [0.9883, 0.4762],
         [0.7242, 0.0776]],

        [[0.4945, 0.3857],
         [0.9883, 0.4762],
         [0.7242, 0.0776]],

        [[0.4945, 0.3857],
         [0.9883, 0.4762],
         [0.7242, 0.0776]]])


In [35]:
c = a * torch.rand(3, 1) # dim 1 is absent, 2nd dim is identical and 3rd dim is different
print(c)

tensor([[[0.4004, 0.4004],
         [0.9877, 0.9877],
         [0.0352, 0.0352]],

        [[0.4004, 0.4004],
         [0.9877, 0.9877],
         [0.0352, 0.0352]],

        [[0.4004, 0.4004],
         [0.9877, 0.9877],
         [0.0352, 0.0352]],

        [[0.4004, 0.4004],
         [0.9877, 0.9877],
         [0.0352, 0.0352]]])


In [36]:
d = a * torch.rand(1, 2) # dim 1 is absent, 2nd dimension is different and 3rd dim is identical
print(d)

tensor([[[0.0905, 0.4485],
         [0.0905, 0.4485],
         [0.0905, 0.4485]],

        [[0.0905, 0.4485],
         [0.0905, 0.4485],
         [0.0905, 0.4485]],

        [[0.0905, 0.4485],
         [0.0905, 0.4485],
         [0.0905, 0.4485]],

        [[0.0905, 0.4485],
         [0.0905, 0.4485],
         [0.0905, 0.4485]]])


Math Operations

In [38]:
# common fucntions -
a = torch.rand(2, 4) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) # Clamps all elements in input into the range [ min, max ].

tensor([[-0.2010,  0.2648,  0.8928, -0.9773],
        [ 0.0365,  0.9614,  0.3090, -0.1713]])
tensor([[0.2010, 0.2648, 0.8928, 0.9773],
        [0.0365, 0.9614, 0.3090, 0.1713]])
tensor([[-0., 1., 1., -0.],
        [1., 1., 1., -0.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0.,  0., -1.]])
tensor([[-0.2010,  0.2648,  0.5000, -0.5000],
        [ 0.0365,  0.5000,  0.3090, -0.1713]])


In [39]:
# Trigonometric functions
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\n Sine and arcsine: ')
print(angles)
print(sines)
print(inverses)


 Sine and arcsine: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [40]:
# Bitwise Operations
print('\n Bitwise XOR: ')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


 Bitwise XOR: 
tensor([3, 2, 1])


In [41]:
print(b)
print(c)

tensor([ 1,  5, 11])
tensor([ 2,  7, 10])


In [45]:
# comparisons -
print('\n Broadcasted, element-wise equality comparison: ')
d = torch.tensor([[1., 2.], [1., 4.]])
e = torch.ones(1, 2)
print(d)
print(e)


 Broadcasted, element-wise equality comparison: 
tensor([[1., 2.],
        [1., 4.]])
tensor([[1., 1.]])


In [46]:
print(torch.eq(d, e)) # it does it element-wise

tensor([[ True, False],
        [ True, False]])


In [48]:
print(torch.ge(e, d))

tensor([[ True, False],
        [ True, False]])


In [52]:
# reductions
print('\n Reduction Ops: ')
print(torch.max(d)) # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d)) # average
print(torch.std(d)) # standard deviation
print(torch.prod(d)) # product
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements


 Reduction Ops: 
tensor(4.)
4.0
tensor(2.)
tensor(1.4142)
tensor(8.)
tensor([1, 2])


In [62]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) # x unit vector
v2 = torch.tensor([0., 1., 0.]) # y unit vector
m1 = torch.rand(2, 2) # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

In [63]:
print(v1)
print(v2)
print(m1)
print(m2)

tensor([1., 0., 0.])
tensor([0., 1., 0.])
tensor([[0.0065, 0.7765],
        [0.3534, 0.7016]])
tensor([[3., 0.],
        [0., 3.]])


In [64]:
print(torch.cross(v2, v1))

tensor([ 0.,  0., -1.])


In [65]:
m3 = torch.matmul(m1, m2)
print(m3)

tensor([[0.0196, 2.3296],
        [1.0602, 2.1048]])


In [66]:
print(torch.svd(m3))

torch.return_types.svd(
U=tensor([[-0.7025, -0.7117],
        [-0.7117,  0.7025]]),
S=tensor([3.2273, 0.7525]),
V=tensor([[-0.2381,  0.9712],
        [-0.9712, -0.2381]]))
